version: '3'
services:
   grafana:
     container_name: grafana
     depends_on:
       - graphite
     links:
       - influxdb:influxdb
       - graphite
     image: grafana
     build: ./grafana
     ports:
       - "8857:3000"
     environment:
       - GF_SECURITY_ADMIN_PASSWORD=admin
       - GF_SECURITY_ADMIN_USER=admin
       - GF_AUTH_ANONYMOUS_ENABLED=true
       - GF_USERS_ALLOW_SIGN_UP=false
       - GF_USERS_ALLOW_ORG_CREATE=false
     restart: always 
   influxdb:
     image: influxdb
     build: ./influxdb
     container_name: influxdb
     ports:
       - "8653:8086"
     expose:
        - 8653
   telegraf:
     image: telegraf
     build: ./telegraf
     container_name: telegraf
     #network_mode: "container:influxdb"
     #volumes:
       # - "c:/:/rootfs/proc:ro"
   #environment:
       # - SYS_PATH_PREFIX=/rootfs
   sitespeed.io:
      image: sitespeedio/sitespeed.io
      command: -V
      privileged: true
      shm_size: 1g
      volumes:
            - ./docker/:/sitespeed.io/
   graphite:
      image: sitespeedio/graphite:1.0.2-2-b
      container_name: graphite
      ports:
        - "2003:2003"
        - "8080:80"
      restart: always
      volumes:
        - whisper:/opt/graphite/storage/whisper
        #- ./graphite/graphite.db:/opt/graphite/storage/graphite.db
        #- ./graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        #- ./graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
        #- ./graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf
   grafana-setup:
      image: sitespeedio/grafana-bootstrap:sitespeed.io-4.6
      container_name: grafana-setup
      links:
        - grafana
      environment:
        - GF_PASSWORD=admin
        - GF_USER=admin
   docker-dind:
      image: docker:dind
      volumes:
        - docker-dind:/usr/local/bin
        - /var/run/docker.sock:/var/run/docker.sock
      container_name: docker-dind
      privileged: true
   jenkins:
      image: jenkins
      build: ./jenkins
      depends_on:
       - docker-dind
      container_name: jenkins
      ports:
       - "8181:8080"
       - "50000:50000"
      volumes:
        - /var/lib/sitespeed.io/:/var/lib/sitespeed.io/
        - docker-dind:/usr/local/bin/dind/
        - /var/run/docker.sock:/var/run/docker.sock
   portainer:
      image: portainer/portainer
      container_name: portainer
      ports:
       - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock  
volumes:
    grafana:
    whisper:
    docker-dind: